version: '3'

services:

  # fluentd:
  #   build: ./fluentd
  #   container_name: fluentd
  #   volumes:
  #     - ./fluentd/conf:/fluentd/etc
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #     - "8888:8888"
  #   networks:
  #     - esnet  
  fluentd-ui:
    build: ./fluentd-ui
    container_name: fluentd-ui
    volumes:
      - ./fluentd-ui/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "8888:8888"
      - "9880:9880"
      - "9292:9292"
    networks:
      - esnet  
  # Elasticsearch requires your vm.max_map_count set to 262144
  # Default will be 65530
  # sysctl -w vm.max_map_count=262144
  # Add this to /etc/sysctl.conf for making it permanent
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    # build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=elasticsearch
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      # - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - esnet  

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - esnet  

volumes:
  esdata1:
    driver: local

networks:
  esnet:    
